### ISSUE TITLE
ALFA AWUS036ACH wireless USB adapter

### ISSUE THREAD

**Issue by feixhq** [arismelachroinos/lscript#29] opened 2017-08-30 18:51 UTC
Hello team, hope your doing fine 
I just received a new AWUS036ACH  and found that the only way I could put it in monitor mode, was by using 

ifconfig wlan0 down	
iwconfig wlan0 mode monitor 
ifconfig wlan0 up

so for the moment, I haven't found a way, to put it in monitor mode within the lazy interface, activating the monitor mode from there won't work with this card, I have another panda one and that works perfectly, is there a workaround for this?

**Comment by arismelachroinos** [comment] 2017-08-30 18:55
Hi sir, 
no team here just me :-P
Thanks for reporting this. I will add an option in settings that you can enable only if you have this card. I will tell you here when it's gonna be up to test it

**Comment by feixhq** [comment] 2017-08-30 18:59
superb bro ! awesome work !

**Comment by arismelachroinos** [comment] 2017-08-30 19:59
@feixhq Thanks !! So when you are in monitor mode the interface is called wlan0 again?? wlan0 in managed mode , wlan0 in monitor mode too?

**Comment by feixhq** [comment] 2017-08-30 21:43
**If I run 
ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up
iwconfig

          eth0      no wireless extensions.
          lo        no wireless extensions.
          wlan0     IEEE 802.11  Mode:Monitor  Frequency:2.412 GHz  Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

**so the card won't be in wlan0mon , haven't found a way to make it work like that not even in 'wifite' for wifite i have to enable the card as previously said .

let me know if something else is neeeded

**Comment by arismelachroinos** [comment] 2017-08-30 22:16
@feixhq last thing, to switch to managed mode again, you do:
ifconfig wlan0 down
iwconfig wlan0 mode managed
ifconfig wlan0 up
??

**Comment by arismelachroinos** [comment] 2017-08-30 22:19
@feixhq  Well 2.0.9 is up , please test and report. The option is in settings menu.

**Comment by feixhq** [comment] 2017-08-30 22:20
yup


     root@kali:~# ifconfig wlan0 down
     root@kali:~# iwconfig wlan0 mode managed
     root@kali:~# ifconfig wlan0 up
     root@kali:~# 
     root@kali:~# iwconfig
     eth0      no wireless extensions.

                lo        no wireless extensions.

               wlan0     IEEE 802.11  ESSID:off/any  
              Mode:Managed  Access Point: Not-Associated   Tx-Power=12 dBm   
              Retry short limit:7   RTS thr:off   Fragment thr:off
              Encryption key:off
             Power Management:off
            

other ways to enable monitoring like  
airmon-ng start wlan0

or 

ifconfig wlan0 down
airmon-ng check kill
airmon-ng start wlan0 

wont work at all for this card =S  (in my case )

**Comment by feixhq** [comment] 2017-08-30 22:21
let me update and try !

**Comment by arismelachroinos** [comment] 2017-08-30 22:23
oh check kill doesnt work either???

**Comment by arismelachroinos** [comment] 2017-08-30 22:24
I think airmon-ng check kill does work alone though. nothing to do with the adapter so it will probably work.

**Comment by arismelachroinos** [comment] 2017-08-30 22:31
Keep in mind you need to set both monitor and managed names to "wlan0"  . Type "interface" to set them up again,

**Comment by feixhq** [comment] 2017-08-30 22:33
**so updated 
** enable wlan0
root@kali:~# iwconfig
lo        no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
eth0      no wireless extensions.


*went to settings 
*activate Alfa * ** *support
*enable wlan0

root@kali:~# iwconfig
lo        no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
eth0      no wireless extensions.

so were good ! on that part , so I go into option 11 

Monitor mode is not enabled.
Do you want to enable monitor mode? (y/n)(Enter=yes): 

I cant pass that option

**Comment by arismelachroinos** [comment] 2017-08-30 22:35
There is actually a limitation to you.if you select the handshake menu , the script searches for wlan0mon in ifconfig. and if it doesnt find it , it tells you to enable it. Because your monitor name is wlan0, it will think that you are in monitor mode even if you arent. I will try to fix that , but for now , before going to the menus: WPS , Handshake    make sure to type "start"  to enable monitor mode.

**Comment by arismelachroinos** [comment] 2017-08-30 22:36
Okay let me see and i will report back.

**Comment by arismelachroinos** [comment] 2017-08-30 22:39
@feixhq  Try this : 
1) type 'interface' and change both names to 'wlan0'
2)type 'start' to enable monitor mode 
3)then go to option 11

**Comment by feixhq** [comment] 2017-08-30 22:39
type 'interface' and change both names to 'wlan0'
2)type 'start' to enable monitor mode
3)then go to option 11

**let me do that right away

**Comment by feixhq** [comment] 2017-08-30 22:44
so set interfaces to wlan0 (2 of them)
type start 
go to 11

***cant pass monitor is not enabled

**Comment by arismelachroinos** [comment] 2017-08-30 22:47
oh i found the problem. So you can help me by posting:
1.  exactly the output of the command 'iwconfig'  when wlan0 is in managed mode

2.  exactly the output of the command 'iwconfig' when wlan0 is in monitor mode

3.  exactly the output of the command 'ifconfig'  when wlan0 is in managed mode

4.  exactly the output of the command 'ifconfig' when wlan0 is in monitor mode

And as for now , to access the WPS menu , open a terminal and type lh3         and to open the Handshake menu, open a terminal and type lh1

**Comment by arismelachroinos** [comment] 2017-08-30 22:54
@feixhq  Also , try the following fix:
1. type 'apt-get install geany'

2. type 'geany /root/lscript/l'

3. go to line 4166 and change it from 'CHECKMON=$(ifconfig | grep "mon")' to 'CHECKMON=$(ifconfig | grep "$WLANNM")'

**Comment by feixhq** [comment] 2017-08-30 23:09
exactly the output of the command 'iwconfig' when wlan0 is in managed mode
wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          


exactly the output of the command 'iwconfig' when wlan0 is in monitor mode
wlan0     IEEE 802.11  Mode:Monitor  Frequency:5.2 GHz  Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off



exactly the output of the command 'ifconfig' when wlan0 is in managed mode
wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether ea:f8:81:80:b3:1d  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


exactly the output of the command 'ifconfig' when wlan0 is in monitor mode

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        unspec EA-F8-81-80-B3-1D-30-3A-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


Ill do this like in 1 or 2 hrs gotta go out of my office for a while 

type 'apt-get install geany'

type 'geany /root/lscript/l'

go to line 4166 and change it from 'CHECKMON=$(ifconfig | grep "mon")' to 'CHECKMON=$(ifconfig | grep "$WLANNM")'

**Comment by arismelachroinos** [comment] 2017-08-30 23:21
Thanks for your time. 
To get the solid fix, go to that line that has the CHECKMON.......... and delete all the line. And put the following in its place
`		if [[ "$ALFA" = "yes" ]]
		then
			CHECKMON=$(iwconfig "$WLANN" | grep "Mode:Monitor")
		else
			CHECKMON=$(ifconfig | grep "$WLANNM")
		fi
		clear
`
and everything should be fine with both the ALFA adapter and every other.
If you have trouble with doing that, it will be included in the next update anyways.

**Comment by arismelachroinos** [comment] 2017-09-02 11:33
@feixhq  Error fixed and update is up.

**Closed by arismelachroinos** 2017-09-02 11:33 UTC

**Comment by feixhq** [comment] 2017-09-02 16:40
@feixhq Error fixed and update is up.

Tested and working bro!

**Comment by sasatefa2009** [comment] 2017-09-04 04:38
@arismelachroinos  

greetings, 
do i also need to replace any code ?
because i also use the same way to enable monitor mode.
any why do you ask for wifi card names at the beginning of the script, i may not be going to use wifi cracking at all.

**Comment by arismelachroinos** [comment] 2017-09-04 06:49
@sasatefa2009 
Hi,
no , you dont need to replace any code yourself. if you download latest version 2.1.0 , you will have to type settings and enable the option for your card. however, all this was an issue when you enabled monitor mode for this card for wifi hacking. So if you dont want to enable monitor mode , you dont even have to enable anything. When the script starts for only the first time, you need to set up the default names for your interfaces. It is so the script knows what to call when you want to perform many procedures that their commands need the script to specify the interface name in order to work.  So if you dont use wifi cracking at all , then just name them wlan0 and wlan0mon and just dont use wifi cracking :P the names arent only for wifi cracking , its general .

**Comment by sasatefa2009** [comment] 2017-09-04 07:33
@arismelachroinos  
Okay sir thank you, but i have a problem when launching nWatch
and its a problem in the script itself because many people have reported the same in the nWatch github page

i get this when i try to launch it

Traceback (most recent call last):
  File "nwatch.py", line 274, in <module>
    iface, ip_addr = pgrntIF()
  File "nwatch.py", line 145, in pgrntIF
    rdata = str(i).split("<splitter>")	
  File "nwatch.py", line 73, in __str__
    self.addresses.get(AF_INET)[0],
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by arismelachroinos** [comment] 2017-09-04 07:56
If many people have reported that it is an issue with nWatch itself, then what can i do about it ? It not on my side and it is completely irrelevant here

**Comment by sasatefa2009** [comment] 2017-09-05 06:43
@arismelachroinos  i thought you might wanna get a look at it, as it would be stupid to put a tool in your script that doesn't work.

**Comment by arismelachroinos** [comment] 2017-09-05 09:25
Sir, when I put a tool in the script, I always test it. The tools works for me. It doesn't work for you. But even if it didn't work for me either, I cannot fix the issue on another script, which is not even the same language as what I use. Please don't demand things that you don't even know how they are done.

**Comment by Ekultek** [comment] 2017-09-05 12:19
The error means that the getitem function is getting None passed to it, there for there's nothing to send to the function and it's failing. This is a Python problem, and has nothing to do with this script as stated by the creator multiple times. Learn to use your computer before you start talking about shit you don't know.

- Thomas Perkins

**Comment by sasatefa2009** [comment] 2017-09-05 12:32
@arismelachroinos 

>  I cannot fix the issue on another script, which is not even the same language as what I use.

I didn't know that, Sorry.

 ---------------------------------------
@Ekultek Thanks for your respond Mr. Thomas Porkins.
I'd appreciate of giving a solution to the problem instead of explaining the cause of the problem.

**Comment by Ekultek** [comment] 2017-09-05 12:35
I explained the cause, now figure out the solution to the cause, once again problem being, the function is getting nothing passed to it. Figure out why it's not getting anything passed to it and it should work.

- Thomas Perkins

**Comment by arismelachroinos** [comment] 2017-09-05 12:35
@sasatefa2009  the solution to the problem will not and should not be discussed on a completely irrelevant topic and repository. Go to tools repository and discuss it there with the developer of that.
