### ISSUE TITLE
./install.sh: line 109: gnome-terminal: command not found and bash: no such file or directory.

### ISSUE THREAD

**Issue by MoudhafferBlg** [arismelachroinos/lscript#206] opened 2020-01-19 17:23 UTC
After uninstalling and reinstalling Lazy script I started getting those two errors. The first one happened once right after installation. the second one( bash : no such file or directory) happens everytime the script says type any key and I type. the script is shutdown and I'm back to root@kali:~#.

**Comment by arismelachroinos** [comment] 2020-01-19 17:29
Do you have the GUI version of Kali?

**Comment by arismelachroinos** [comment] 2020-01-19 17:30
type `apt-get install -y gnome-terminal`

**Comment by MoudhafferBlg** [comment] 2020-01-19 17:31
> type `apt-get install -y gnome-terminal`

Still getting bash : no such file or directory

**Comment by arismelachroinos** [comment] 2020-01-19 17:35
give me the output of `which bash`

**Comment by MoudhafferBlg** [comment] 2020-01-19 17:36
Output : /usr/bin/bash

**Comment by arismelachroinos** [comment] 2020-01-19 18:48
`cat /etc/os-release`

**Comment by MoudhafferBlg** [comment] 2020-01-19 18:50
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.1"
VERSION_ID="2020.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by arismelachroinos** [comment] 2020-01-19 18:52
`ls /bin | grep "bash"`

**Comment by MoudhafferBlg** [comment] 2020-01-19 18:53
bash
bashbug
dh_bash-completion
rbash

**Comment by arismelachroinos** [comment] 2020-01-19 18:55
When are you getting the error? Just by typing `l` ?

**Comment by arismelachroinos** [comment] 2020-01-19 18:55
Did the script install successfully?

**Comment by MoudhafferBlg** [comment] 2020-01-19 18:58
Nope, typing `l` I can launch lazy script but for example if I choose `if` it shows the information then says _press any key_. Upon pressing a key I should be returned to the main script menu(this used to happen fine before reinstalling) instead it just outputs that error and exits the script. 

> Did the script install successfully?

I would like to this so, yes.

**Comment by arismelachroinos** [comment] 2020-01-19 19:00
Ok got it. Is there an output when you type `bash` on a terminal?

**Comment by arismelachroinos** [comment] 2020-01-19 19:15
Actually give me the output of `echo $PATH`

**Comment by arismelachroinos** [comment] 2020-01-19 19:17
And give me this output as well `ls /bin/lscript`

**Comment by MoudhafferBlg** [comment] 2020-01-19 20:09
> Actually give me the output of `echo $PATH`

/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin



> And give me this output as well `ls /bin/lscript`

l  lh1  lh2  lh21  lh3  lh31  lh4  lh41  lh42  lh43

**Comment by MoudhafferBlg** [comment] 2020-01-23 14:30
Still no luck with this error. Tried installing the script on a fresh vm. Same error. And when trying to do an arp scan, 'scan' I get error 6. no parameters passed

**Comment by arismelachroinos** [comment] 2020-01-23 17:05
I just found the cause. It will be fixed soon.

**Comment by arismelachroinos** [comment] 2020-01-23 17:12
Please re-download and re-install and report back if it is okay now. (You cannot update from lscript because I did not change the version. You have to redownload manually)

**Comment by arismelachroinos** [comment] 2020-01-23 17:15
@MoudhafferBlg  The "error 6. no parameters passes" made me understand the reason of the errors. It was the same error so they should be all fixed now.

**Comment by arismelachroinos** [comment] 2020-01-24 15:59
@MoudhafferBlg  does it work now?

**Comment by MoudhafferBlg** [comment] 2020-01-27 10:03
Nope it doesn't. Kinda giving up hope on vm

**Comment by arismelachroinos** [comment] 2020-01-27 11:06
@MoudhafferBlg  You have to remove the script and redownload it. The error is fixed, you just have to get the new script.

**Comment by MoudhafferBlg** [comment] 2020-01-27 11:24
Confirmed this. Errors are no longer present.

**Comment by arismelachroinos** [comment] 2020-01-27 11:25
Thank you too for reporting this.

**Closed by arismelachroinos** 2020-01-27 11:25 UTC
