### ISSUE TITLE
is this right  Waiting for beacon from F4:00:00:00:00:00 ?

### ISSUE THREAD

**Issue by sasatefa2009** [arismelachroinos/lscript#31] opened 2017-09-05 00:47 UTC
All the WPS enbled wifi says the same thing below when i try to crack it
Waiting for beacon from F4:00:00:00:00:00

and how can i install WiFi autopwner if i'm in monitor mode ?

**Comment by arismelachroinos** [comment] 2017-09-05 01:06
I haven't seen the  f4 thing before. and I cannot reproduce it, today I used all the WPS options myself. The issue with the installation of wifiautopwner is my stupidity. It will be fixed in the next version, however you can install it by going to TOOLS - > INSTALL REINSTALL .  What about the monitor mode though? it cannon be read by the script??

**Comment by arismelachroinos** [comment] 2017-09-05 01:10
what wifi adapter are you using? also you are using the letest kali?

**Comment by sasatefa2009** [comment] 2017-09-05 01:13
@arismelachroinos 
its because i've chosen the 'ALFA AWUS036ACH support' in the settings,
i found that even wash doesn't read this method and requires wlan0mon as the monitor mode.

but when i try to crack any wlan with wps mode enabled it says this 
`Waiting for beacon from F4:00:00:00:00:00`

and also i cant copy anything from the wash external scanning windows that open.
and after it finish, the results is not printed in the original screen

**Comment by arismelachroinos** [comment] 2017-09-05 09:19
Do not enable the alfa setting in settings. thats your issue.

**Closed** 2017-09-05 12:31 UTC

**Comment by sasatefa2009** [comment] 2017-09-12 12:04
@arismelachroinos 
sorry, i had to open this again as the wps cracking is not workings.
first: when scanning with wash and pressing (Ctrl+C), the founded AP's are not copied to the original screen.
second: if i choose a number from what i could see in the new "wash" opened screen and tried any wps attack method it always make like this

Reaver v1.6.1 WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>

[+] Waiting for beacon from F4:00:00:00:00:00
[+] Switching wlan1mon to channel 1
[+] Switching wlan1mon to channel 2
[+] Switching wlan1mon to channel 3
[+] Switching wlan1mon to channel 4
[+] Switching wlan1mon to channel 5
[+] Switching wlan1mon to channel 6


I'm using TL-WN722N

**Comment by arismelachroinos** [comment] 2017-09-12 13:11
disable the alfa setting in settings.

**Comment by sasatefa2009** [comment] 2017-09-12 17:48
@arismelachroinos  i already did
may you please try with your pc ?

**Comment by arismelachroinos** [comment] 2017-09-12 20:44
everything is working on my side sir
